@startuml
' 定义顺序
participant ServiceBean
participant ServiceConfig
participant AbstractInterfaceConfig
participant AbstractProxyFactory
participant Protocol

ServiceBean -> ServiceBean :onApplicationEvent
ServiceBean -> ServiceConfig :export
ServiceConfig -> ServiceConfig :doExport
ServiceConfig -> ServiceConfig :checkDefault
ServiceConfig -> ServiceConfig :checkApplication
ServiceConfig -> ServiceConfig :checkRegistry
ServiceConfig -> ServiceConfig :checkProtocol
ServiceConfig -> ServiceConfig :appendProperties
ServiceConfig -> ServiceConfig :checkStubAndMock
ServiceConfig -> ServiceConfig :doExportUrls
ServiceConfig -> AbstractInterfaceConfig :loadRegistries
AbstractInterfaceConfig ->  ServiceConfig :List<URL> registers
ServiceConfig -> ServiceConfig :doExportUrlsFor1Protocol
note left: 在单个协议上注册、暴露
ServiceConfig -> AbstractProxyFactory :getInvoker
ServiceConfig -> Protocol :export
ServiceConfig -> Wrapper :getWrapper
Wrapper -> Wrapper :makeWrapper







'onApplicationEvent(ContextRefreshedEvent event)

@enduml